name: Deploy GitHub Pages from Repo octacorn-domain-for-sale

on:
  workflow_dispatch:  # Izinkan trigger manual
  push:
    branches: [ "main" ]  # Ganti dengan branch sumber Anda (misal: main, master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Artifact from Repo octacorn-domain-for-sale
        uses: actions/upload-pages-artifact@v3
        with:
          # Path ke subdirektori yang ingin dideploy
          path: "octacorn-domain-for-sale/"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # Pastikan versi benar
