name: Deploy GitHub Pages from Repo octacorn-domain-for-sale

on:
  workflow_dispatch:  # Izinkan trigger manual
  push:
    branches: [ "main" ]  # Ganti dengan branch sumber Anda (misal: main, master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    permissions:
      pages: write
      id-token: write
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact from Repo octacorn-domain-for-sale
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: |
            index.html
            style.css

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
